### ISSUE TITLE
Response times section should not have left padding

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1756]
See /legal/ubuntu-advantage/service-description and scroll to section 3. Response times - this section should align with the rest of the content, without left padding

The same is happening with sections 4 and 5

And from the first column in Appendix 2 to section 7

**Comment by barrymcgee** [comment]
Fixed here: http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/ubuntu-advantage/service-description

Waiting on stakeholder signoff before merging.

**Comment by yaili** [comment]
Sections 4 and 5, and from "Table of machines under support" to "3. Support severity levels", and some other sections, are not fixed yet. It seems like the col-8 are adding left margin.

**Comment by barrymcgee** [comment]
@yaili Sorry, you're right. Try again now, should be sorted? http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/ubuntu-advantage/service-description
