### ISSUE TITLE
'Search' lettering slightly cut off (new Vanilla pages)

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#1861]
'Search' lettering is slightly cut off on new Vanilla pages

![screenshot from 2017-05-28 14-51-55](https://cloud.githubusercontent.com/assets/3178485/26529310/a339d8ae-43b5-11e7-9f66-a01237c3ab8d.png)
![screenshot from 2017-05-28 14-52-07](https://cloud.githubusercontent.com/assets/3178485/26529311/a33a9960-43b5-11e7-97e2-7cfcc71b3a77.png)

Firefox 53.0.3 on Ubuntu 17.04

---
*Reported from: https://www.ubuntu.com/download*

**Comment by Ads20000** [comment]
Also maybe consider changing the lettering of that text back to white?

**Comment by deadlight** [comment]
This issue was addressed as part of the Vanilla migration. Apologies for not replying to your report at the time.

**Comment by Ads20000** [comment]
Cleared my cache and removed the ubuntu.com cookie and still have this bug (also it's on all pages now because of the migration).

![screenshot from 2017-08-10 18-11-18](https://user-images.githubusercontent.com/3178485/29182672-ab95aef2-7df7-11e7-8d99-ca85200d6932.png)
![screenshot from 2017-08-10 18-15-17](https://user-images.githubusercontent.com/3178485/29182732-e3fcfe62-7df7-11e7-930c-c12415a676bf.png)

**Comment by Ads20000** [comment]
Seems to only really apply on 100% zoom and 67% zoom (very obvious at 67%, which you get to by pressing `Zoom -` three times on Firefox). My resolution is 1600x900 and I'm now on Firefox 54.0.
