### ISSUE TITLE
XSS in the MoinMoin wiki software

### ISSUE THREAD

**Issue by gunnarhj** [canonical-websites/www.ubuntu.com#4246]
An issue with the wikis at https://wiki.ubuntu.com and (probably) https://help.ubuntu.com/community/CommunityHelpWiki was reported in this bug:

https://bugs.launchpad.net/ubuntu-docs/+bug/1797927

In short it's about XSS issues in version 1.9.8 of the MoinMoin software (the version currently used to run the wikis on those Ubuntu sites), and the natural solution is to upgrade MoinMoin. The Ubuntu documentation team does not have access to do this, which is the reason I filed this issue.

Possibly this is not the right issue tracker; if not I ask you to please move it to the right tracker.

Please see the LP bug for further details.

**Comment by pmahnke** [comment]
I have filed this for @gunnarhj in the RT system for IS - https://portal.admin.canonical.com/C114892/

Closing here.

**Comment by pmahnke** [comment]
@gunnarhj 	

looks like this is now fixed

> I've finished porting the patch from Xenial to our Precise backports repository.
> 
> I updated wiki.ubuntu.com, wiki.maas.io, and help.ubuntu.com with the patched version.
>

**Comment by gunnarhj** [comment]
Thanks @pmahnke! I asked the OP of the original bug report to confirm.

**Comment by lorenzodifuccia** [comment]
The problem (XSS) is still present, same behavior.
  
![XSS](https://raw.githubusercontent.com/lorenzodifuccia/cloudflare/master/Images/vulns/wiki_ubuntu/wiki_ubuntu_xss_01.png)

**Comment by jetpackdanger** [comment]
This turned to be a bug in our theme's code and not in Moin. I've fixed the theme bug and confirmed that the test case supplied in the Launchpad bug no longer succeeds.

**Comment by lorenzodifuccia** [comment]
Yes, it seems fixed.
You added some escape function that gets the job done.
